#!/bin/bash
# Seed Script Helper
# This file provides quick reference for common seeding operations

echo "📚 Smart Lodging - Database Seed Script Guide"
echo "=============================================="
echo ""
echo "🌱 Quick Commands:"
echo ""
echo "1. Development Mode (Recommended):"
echo "   cd backend && npm run seed"
echo ""
echo "2. Production Mode (After build):"
echo "   cd backend && npm run build && npm run seed:prod"
echo ""
echo "✅ Test Accounts Created:"
echo "   Admin:  admin@smartlodging.com / admin123"
echo "   Host:   host@smartlodging.com / host123"
echo "   Client: client@smartlodging.com / client123"
echo ""
echo "📦 What Gets Seeded:"
echo "   - 3 test user accounts with different roles"
echo "   - 14 sample lodgings with images and details"
echo "   - Automatically skips duplicates (idempotent)"
echo ""
echo "🔗 Access Points After Seeding:"
echo "   Frontend:  http://localhost:3000"
echo "   Admin Panel: /admin (use admin account)"
echo "   Host Dashboard: /host (use host account)"
echo ""
echo "💡 Pro Tips:"
echo "   - Run seed script after initial docker-compose setup"
echo "   - Use test accounts to demo role-based features"
echo "   - Safe to run multiple times (won't create duplicates)"
echo ""
